### ISSUE TITLE
For data dictionary export, also include a "simple" version that combines across variables/domains

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#385]
It might be nice to have a "simple" (single file) data dictionary that comes out of Slice and can be shared.

Many columns in "Variables" could be dropped/discarded (mostly relevant for styling or checking during entry) and the biggest "change" would be folding the domain options into the variables sheet itself.

**Comment by remomueller** [comment]
Looking at this, would it need to be a CSV, or are you thinking a readable version in more of a document format?

**Comment by remomueller** [comment]
Potentially create the codebook using `prawn` gem to reduce depdency on LaTeX.

```ruby
require "prawn"

Prawn::Document.generate("hello.pdf") do
  text "Hello World!"
end
```
