### ISSUE TITLE
On subject-event index, possibly collapse completed events in favor of highlighting incomplete (usually latest) event

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#427]
For a project like PATS we are going to end up with ~15 events per subject. When a subject is halfway through the study it's likely unnecessary to give much screen real estate to the screening and baseline visits. 

One option might be to collapse completed/full events and then allowing them to be expanded as necessary by the user. 

Another option on the subject-event index might be to simply show the latest event.

**Comment by remomueller** [comment]
Hi @mrueschman, I tried both approaches, but the extra click to expand events seemed more annoying than just scrolling past the list of events. I'm moving this issue to 0.43.0 so we can see how this works with the new interface before potentially trying to hide "completed" events again.

**Comment by mrueschman** [comment]
No longer under consideration.
