### ISSUE TITLE
New question type: ranking question

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#500]
Premise: You have a list of 5 animals and you want the respondent to rank them in order of how cute they think the animals are. 1 being the cutest and 5 being the least cute. 

User would input a list of items to rank when building the question on a design. Not sure how it would get stored in the backend; maybe a column for each item to be ranked (e.g. `rank_cute_animal_horse`, `rank_cute_animal_dog`) along with the numeric position that the user set for the value?

Examples from LimeSurvey and SurveyMonkey:

https://www.youtube.com/watch?v=VoA2Sl42NnI
https://www.surveymonkey.com/r/Preview/?sm=XtvshH63i_2BmgbPEFqa7IrCrGcvxCyXJOr4aqFRqKFta2Tuf0auVt4kG30qrpT3fJ

**Comment by remomueller** [comment]
Note to self, this would be stored in `Response` table similar to checkboxes, and the position is what would be stored there.
