### ISSUE TITLE
For repeated designs on an event, distinguish with something "better" than created date

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#605]
![image](https://cloud.githubusercontent.com/assets/707167/24167293/a661a19a-0e4c-11e7-9f11-c019f1be55e9.png)

For CALYPSO we are going to have a few weeks of "My Sleep and Yoga" Logs per participant. They will likely be entered at a later date and all on the same date, so the "Created At" date on the right would be the same for each Log.

The first variable on the Log design is "Log Date". It might be more prudent to display this on the Event index, and even more so to have the individual log sheets ordered based on this (lest you inadvertently skip a log during data entry and enter it at the end).

I'm not sure if the "distinguishing" field needs to be explicitly set or whether it could (always) be the first variable on the Design of interest.

**Comment by remomueller** [comment]
Perhaps a flag for designs that says "Use first date on design"? or something like that?

**Comment by mrueschman** [comment]
That thought occurred to me as well -- it would satisfy this particular use.

Then I imagined another scenario where you were taking the same measurement multiple times on the same day. Like for the JAZZ trial they did 4 or 5 "mean wakefulness tests" back to back. These were all part of a single "study visit" (so 1 event). Assuming you had a separate sheet for each test, the dates would still all be the same. Maybe in that instance you would want them differentiated by starting time (another design field) or simply by "# in sequence" (another field on design, e.g. "Test Number: [1, 2, 3, 4, 5]".

**Comment by remomueller** [comment]
Hmm, good point. I wonder if there's a better way of addressing that then, perhaps an interpolated string (template) that you could set on the design level that would use variable names, ex:

`#{ciw_study_visit_date}` would give you `23-MAR-2016` based on your formatting of the variable.

`#{sequence_number}` would give you `1` if sequence number was an integer.

**Comment by mrueschman** [comment]
That could work!

**Comment by mmorrical** [comment]
I really like the idea of having a primary variable that can be set to show on the overview page. Would be great for denoting phone calls listed under the wrong event date or any measures that have a primary variable of interest (ESS score, ISAAC global wheezing score, age/sex/bmi from screening forms, etc).
