### ISSUE TITLE
Revisit error validation messaging (maybe ranges themselves, too)

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#639]
Some discussion here: https://github.com/sleepepi/sleepinnovate.org/issues/30

Right now an error on a numeric field might look like:

![image](https://user-images.githubusercontent.com/707167/29977553-c622f96c-8f0b-11e7-9a1b-21db195e2d64.png)

We are moving more and more toward having direct participant entry, so validations like this might confuse more than help in terms of letting people what they need to do next. Perhaps we could eliminate both the tooltip that displays range and rewrite the error messaging to include the range within the message, e.g. "Please enter a value between 80 and 200."

We would want the messaging to be understandable by study staff and participants alike. There are lots of different permutations of range checking, which might require different sorts of phrasing and error messaging. These could be gone through 1-by-1.

Other potentially related issues/discussions to have down the line:

- Ranges? Do we want soft and hard ranges long term? Or only one range?
- A possibly neat innovation for a date range would be to allow "today" to be set as a minimum or maximum. If I have a variable like, "When were you diagnosed with insomnia?" the logical maximum is the current date (the minimum is harder to discern). People might run with this sort of request and then want to do "today + 10 days".

**Comment by remomueller** [comment]
One issue to think about with the "today" as a range would be someone updating the sheet later, would it enforce the new date? Validate against when the value was entered initially, or when the sheet was created?

**Comment by remomueller** [comment]
Also, just a note the validation passes back two values, a display of the value with units and an optional error message

**Comment by remomueller** [comment]
One more thought, I've been wondering if the error message should replace a field note, instead of pushing it down.

**Comment by mrueschman** [comment]
Hm, yes, I hadn't thought of how such a validation might work for both the initial creation and later editing!

Replacing the field note on error seems like it would be worth trying.

**Comment by remomueller** [comment]
Thinking about this a bit further, we COULD have the following setting for date variables, that wouldn't break as the date changes: A checkbox that says "Disallow future dates".

**Comment by mrueschman** [comment]
"Disallow future dates" seems pretty clear/concise.

**Comment by remomueller** [comment]
Disallow future dates issue now here https://github.com/remomueller/slice/issues/734.
