### ISSUE TITLE
Look for 'missing' sheets that potentially should be deleted

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#645]
Example case:

https://tryslice.io/projects/pats/sheets/43726 (completed sheet)
https://tryslice.io/projects/pats/sheets/43717 (set as missing, but obscured from view when perusing data entered for this subject)

I am now deleting 43717 so that it does not come out (as a missing sheet) in the data export.

**Comment by remomueller** [comment]
So if I understand correctly, what you are looking for a duplicate sheets for a design/event where one is set as missing?

**Comment by mrueschman** [comment]
I think that's right, though the memory of this situation (which seems strange) isn't entirely clear!
