### ISSUE TITLE
Add "Branching Logic" into "variables" data dictionary export file

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#648]
Other consideration: Do we need both the "designs" and "variables" files in the data dictionary export? The "designs" file contains only 1 distinct column (not in "variables"): "Branching Logic".

Possibly: Add "Branching Logic" into the "variables" file and drop the "designs" file? Also, in the exported version, it would be helpful to have the translated version of the branching logic. E.g. 

do_you_have_a_gender == 2

instead of

#{20836} == 2

![image](https://user-images.githubusercontent.com/707167/34485075-a324817e-ef96-11e7-9f3f-307ed0a72e76.png)

**Comment by remomueller** [comment]
I may do this one in stages, and first add the branching logic to the variables file. The only wrinkle here is that we still have variables that can span across multiple designs.
