### ISSUE TITLE
Branching logic and scale variables - answer option labels won't show up (edge case)

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#649]
Hypothetical: Create a design with 11 questions. The first question asks if subject is Male or Female. Questions 2-6 show up if Male and Questions 7-11 show up if Female. If questions 2-11 all use the same domain and are set as Scale, then when choosing Female the user will not be shown the option labels (i.e. column headers). 

Slice is setting questions 2-11 as part of the same scale, so to speak, yet the branching logic only shows the second half of the questions when Female is selected.

Anyway, this happened on this EASY questionnaire. https://tryslice.io/projects/easy/designs/strengths-and-difficulties-questionnaire

My simple workaround was to add subsections to break up portions of the scale questions.

**Comment by remomueller** [comment]
The column headers would have to be changed to render dynamically based on if there are any scale variables below it that are displayed or not. Would require additional client-side JS. The same logic would also need to be used in generating the PDFs using server-side JS. I do want to do another pass at all the JS that is currently running on a sheet when responses are entered to ensure that there isn't too much extra going on. (Branching logic, validations, calculations, autocompletion).  Large sheets currently have noticeable lag on less powerful devices, that needs to be addressed before adding something like this.
