### ISSUE TITLE
Show subject code in URL instead of internal Slice subject number

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#652]
![image](https://user-images.githubusercontent.com/707167/36103484-6772cff2-0fdd-11e8-9cca-07397db43b8e.png)

Instead of having 19838 in the URL, replace with "CoolSubject" since the /subjects index is nestled underneath the project slug (and projects can't have duplicate subjects).

**Comment by remomueller** [comment]
In order for this to work, it'd probably be helpful to put some constraints on subject codes. Do you have a reasonable subset of characters that would work from formats you've seen?

My thought may be something like:

- `a-zA-Z` (case insensitive), so coolsubject is the same as CoolSubject
- `0-9`

**Comment by mrueschman** [comment]
Seems reasonable. Emoji subject codes would be cool, though!

Yeah, my next question would have been whether we have existing subjects that violate the proposed constraints.

**Comment by remomueller** [comment]
We have a total of 542 out of roughly 20,000 subjects. They include the following symbols (most of which can most likely be replaced):
- `@`
- ` ` (Blank Space)
- `.`
- `(`
- `)`
- `+`
- `\` (Backtick!)

**Comment by remomueller** [comment]
Hey, 😁 we can add emoji into subject codes as long as your SAS can handle it when it's exported to CSV.

| Subject Code | Age |
|---------------|-----|
| 🍀 | 5 |
| 💩 | 200 |

**Comment by remomueller** [comment]
Moving this one to the next release as well, it should work, but I want to make sure we catch any places this may work incorrectly (handoffs / public surveys / AEs etc)
