### ISSUE TITLE
Add unlock and edit option to sheet show page for project editors

### ISSUE THREAD

**Issue by remomueller** [sleepepi/slice#673]
From @mmorrical:

> It would also be great if there was any reasonable way to give people with unlocking permissions a choice like "unlock and edit". When I need to update a bunch of sheets after DSMB reports, from the list of sheets I've identified it goes:
1.) click sheet name (page loads)
2.) click Sheet Locked
3.) click Unlock for 1 Week (page reloads)
4.) click Actions
5.) click Edit (page reloads)
6.) begin editing
> 
> Both the clicking and page loads add up over 100+ sheets

**Comment by mmorrical** [comment]
Thanks Remo. If I could go straight from sheet index to editing as a project editor that would be a huge timesavings.
