### ISSUE TITLE
Add more functionality to Team page

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#737]
Right now Team Page lists Name and Role (which is just Owner/Member - not all that useful). Actions per user include Show Roles and Remove from project.

Things to consider as enhancements:

- [x] Search and filter (e.g. searching by name could drill down to staff member instead of scrolling through long list)
- [x] Add roles (show and delete capability?) to index itself
  - [x] Show roles
  - [x] Delete roles
- [x] Add ability to filter list of users down by Site and/or Role Types

**Comment by mrueschman** [comment]
cc @mmorrical to see if he has more input/suggestions.

**Comment by remomueller** [comment]
Didn't add "delete" capability for roles, although you can still remove them by clicking through to the team member (View Roles). Also, haven't added filters by Site/Role Types at this time.
