### ISSUE TITLE
Export sheets associated with new AE module

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#758]
Can test with LOFT-HF Certification, which now has AEs in the new module and associated sheets. There are sheets entered by reporters (highest priority) and sheets entered by team reviewers (lower priority).

**Comment by remomueller** [comment]
So with the next update, the following sheets will be exportable, those created by `reporters`, `reviewer admins`, and `principal reviewers`. The "duplicate" sheets by `reviewers` are specifically excluded. Let me know if that needs to be changed.

**Comment by remomueller** [comment]
Also, a side-effect of this change is that the sheets index now includes AE sheets, let me know if those should be hidden again there.
