### ISSUE TITLE
Extend data report API to handle additional report types

### ISSUE THREAD

**Issue by remomueller** [sleepepi/slice#759]
Make sure reports from PATS portal can be covered by new data API

---

**Completed in v78**
- [x] Charts "screened", "eligible", "consented" by month and by site
- [x] Number "consented", "eligible", "randomized", etc
- [x] Report card chart, "event completion" by "site"
- [x] Data inconsistencies, "checks" by "site"
- [x] Note: X of the total X screened have not yet been assigned a final eligibility status.
- [X] Demographics reports (filter by "randomized" in expressions engine).

---

**Completed in v76**
- [x] Randomizations by month and by site

**Comment by mrueschman** [comment]
@mmorrical reported that a couple users inquired about some of the other reports no longer updating (e.g. Consented by month by site). Good to keep this around, though I think the AE-related issues in 78 are probably a higher priority.

**Comment by remomueller** [comment]
@mrueschman the majority of the reports are now updated live (once per day).
