### ISSUE TITLE
Starting an export only pushes you to export show page when export finishes (causes timeouts on lengthy exports)

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#763]
It used to be when starting an export you would go to show page and completion bar would dynamically update and fill as export completed. The bar changed to the .ZIP file download link when finished.

Now if you launch an export that is going to take more than a few seconds the user will stay on the New Export screen with the browser spinning until an eventual timeout if it goes >60 seconds or so.  The export is still running and will eventually finish.

**Comment by remomueller** [comment]
It looks like forking a process isn't working in the new environment, so it's running things in the foreground and waiting for a response. Changing that over to use ActiveJob along with Redis may be a better solution.
