### ISSUE TITLE
For Site Editors, team roles list as "Project" Editor

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#767]
![image](https://user-images.githubusercontent.com/707167/58975961-51469300-8794-11e9-8534-230d892330ce.png)

The user was invited as a Site Editor for each site, yet when listing roles on Team/user page the wording says "Project Editor".

**Comment by mmorrical** [comment]
This wording appears to be tied to the roles and is throughout Slice.
Currently inviting new users looks like this:

[cid:image002.jpg@01D51BA5.8874FDE0]
