### ISSUE TITLE
Allow past AEs to be more easily browsed

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#770]
As part of the new AE module and Team Reviewing, one thing that reviewers will probably find important is the ability to browse through prior AEs for the same subject. Information gleaned from past AEs might help inform decisions about the AE currently under review.

This applies to members of AE teams, so the lefthand bar seen by project/site editors wouldn't suffice for this purpose.

Quick thought: Add another tab to the current Overview/Documents/Log in the module for "Past Events" (or some other phrasing). On this page list out the AE #s, created dates, and short descriptions for past AEs for the same subject, with links to open those AEs for some sort of review. This last issue might be tricky since right now a role like the Team Reviewer only "sees" assigned to him/her.

**Comment by remomueller** [comment]
Team reviewers see all events assigned to their team, regardless of whether they have been assigned as a reviewer or not. I made the tab show conditionally (if there are other events for that subject). The tab is labeled as History, shows all events, and also lists the current event that's being viewed.
