### ISSUE TITLE
Check pulling back more results than expression shows

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/slice#774]
Noted by @mmorrical. 

https://sliceable.org/projects/pats/sheets?search=checks:subject-is-consented-race-is-missing

7 results at the moment

Looking at check expression editing (https://sliceable.org/editor/projects/pats/checks/subject-is-consented-race-is-missing) shows 4 results.

I think the mismatched sheets ONCE had a "-9" for race, but then had race added in a later transaction. Here's an example sheet: https://sliceable.org/projects/pats/sheets/113648

Archiving/unarchiving check or editing sheets doesn't seem to get the check message to drop from the sheets that now have a valid race.

**Comment by remomueller** [comment]
This is due to cronjobs not running. They were running twice across multiple servers, and the fix to get the running only on the job servers did not work. Fix going into place to restrict when the jobs run: da5785786f4e038a1a28aa94bd813f2cba4f1a2d
