### ISSUE TITLE
Add email triggers to the adverse event reporting workflow

### ISSUE THREAD

**Issue by remomueller** [sleepepi/slice#779]
- [ ] ~~Check if notification is needed for when the adverse event is opened, sent for review, or both.~~

**Comment by mrueschman** [comment]
I think let's go with emails across the board for now. Maybe we'll also hone the "AE Inbox" over time as well (to better bring pending/unresolved things to the forefront for users).

How about we add the following triggers for email notifications?

- [ ] When AE sent to team, notify AE Team Managers
- [ ] When AE assigned for review, notify AE Team Reviewers and AE Principal Reviewer
- [ ] When AE Admin opens request for information, notify AE reporter
- [ ] When AE reporter marks request resolved, notify AE Admin
- [ ] When AE Team reviewer submits review, notify AE Team Manager
- [ ] When AE Team person (manager/reviewer?) opens request for information, notify AE Admin
- [ ] When AE Admin marks request resolved, notify AE Team person
